import PDFDocument from 'pdfkit';

export interface PDFExportData {
  boardTitle: string;
  notesContent: string;
  authorName?: string;
  createdAt?: string;
  elementCount?: number;
}

export const generateMeetingNotesPDF = (data: PDFExportData): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers: Buffer[] = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', (err) => reject(err));

    // Header
    doc
      .fillColor('#2563EB')
      .fontSize(24)
      .text('Meeting Summary & Whiteboard Notes', { align: 'center' });
    doc.moveDown(0.5);

    doc.strokeColor('#CBD5E1').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    // Board Metadata
    doc.fillColor('#1E293B').fontSize(14).text(`Board Title: ${data.boardTitle}`);
    if (data.authorName) doc.fontSize(10).fillColor('#64748B').text(`Generated by: ${data.authorName}`);
    doc.fontSize(10).fillColor('#64748B').text(`Date: ${new Date().toLocaleDateString()}`);
    if (data.elementCount !== undefined) {
      doc.fontSize(10).fillColor('#64748B').text(`Whiteboard Canvas Objects: ${data.elementCount}`);
    }
    doc.moveDown(1.5);

    // Notes Header
    doc.fillColor('#0F172A').fontSize(16).text('Collaborative Meeting Notes:', { underline: true });
    doc.moveDown(0.5);

    // Notes Body
    const cleanNotes = data.notesContent || 'No meeting notes recorded for this session.';
    doc.fillColor('#334155').fontSize(12).text(cleanNotes, {
      align: 'left',
      lineGap: 4,
    });

    // Footer
    doc.moveDown(2);
    doc.fillColor('#94A3B8').fontSize(9).text('Generated with Collaborative Whiteboard & Meeting Platform', {
      align: 'center',
    });

    doc.end();
  });
};
