import PDFDocument from 'pdfkit';

export interface PDFExportData {
  boardTitle: string;
  notesContent: string;
  authorName?: string;
  createdAt?: string;
  elementCount?: number;
  canvasImageBase64?: string;
}

export const generateMeetingNotesPDF = (data: PDFExportData): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers: Buffer[] = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', (err) => reject(err));

    // Title Header
    doc
      .fillColor('#2563EB')
      .fontSize(22)
      .text('Meeting Summary & Whiteboard Notes', { align: 'center' });
    doc.moveDown(0.5);

    doc.strokeColor('#CBD5E1').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.8);

    // Board Metadata
    doc.fillColor('#1E293B').fontSize(14).text(`Board Title: ${data.boardTitle}`);
    if (data.authorName) doc.fontSize(10).fillColor('#64748B').text(`Generated by: ${data.authorName}`);
    doc.fontSize(10).fillColor('#64748B').text(`Date: ${new Date().toLocaleDateString()}`);
    if (data.elementCount !== undefined) {
      doc.fontSize(10).fillColor('#64748B').text(`Whiteboard Objects Count: ${data.elementCount}`);
    }
    doc.moveDown(1);

    // Canvas Image Diagram (if provided)
    if (data.canvasImageBase64) {
      try {
        const base64Data = data.canvasImageBase64.replace(/^data:image\/\w+;base64,/, '');
        const imgBuffer = Buffer.from(base64Data, 'base64');

        doc.fillColor('#0F172A').fontSize(14).text('Whiteboard Canvas Diagram:', { underline: true });
        doc.moveDown(0.5);

        doc.image(imgBuffer, {
          fit: [500, 260],
          align: 'center',
          valign: 'center',
        });
        doc.moveDown(1);
      } catch (e) {
        console.error('[PDF Generator] Error embedding canvas image:', e);
      }
    }

    // Meeting Notes Section
    doc.fillColor('#0F172A').fontSize(14).text('Collaborative Meeting Notes:', { underline: true });
    doc.moveDown(0.5);

    const cleanNotes = data.notesContent || 'No meeting notes recorded for this session.';
    doc.fillColor('#334155').fontSize(11).text(cleanNotes, {
      align: 'left',
      lineGap: 4,
    });

    // Footer
    doc.moveDown(2);
    doc.fillColor('#94A3B8').fontSize(9).text('Generated with Collaborative Whiteboard Platform', {
      align: 'center',
    });

    doc.end();
  });
};
